image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - docker info
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY


# build stage

build:
  stage: build
  script:
    - docker build --pull -t "$REGISTRY_IMAGE/api" ./api
    - docker push "$REGISTRY_IMAGE/api"
    - docker build --pull -t "$REGISTRY_IMAGE/app" .
    - docker push "$REGISTRY_IMAGE/app"
  only:
    - master


# deploy stage

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - which ssh-agent || (apk add --update openssh-client)
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H dev.steffbeckers.eu >> ~/.ssh/known_hosts
  script:
    - scp -r ./docker-compose.yml root@dev.steffbeckers.eu:~/compositions/$PROJECT_PATH/docker-compose.yml
    - ssh root@dev.steffbeckers.eu "docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}; cd ~/compositions/$PROJECT_PATH/; docker pull "$REGISTRY_IMAGE/app"; docker pull "$REGISTRY_IMAGE/api"; docker stack deploy --with-registry-auth --compose-file docker-compose.yml cats"
  only:
    - master
