version: "3.7"

services:
  app:
    image: registry.steffbeckers.eu/steffbeckers/cats/app
    networks:
      - reverse-proxy_default
      - default
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - rethinkdb
      - redis
      - api
  api:
    image: registry.steffbeckers.eu/steffbeckers/cats/api
    environment:
      - REDIS_URL=redis://redis/0
      - JWT_SECRET=470ffc3e5f229a043f5c849eb58d2849e6d11f9027f15ca54bf7d701a8c1a78f
    networks:
      - reverse-proxy_default
      - default
    # deploy:
    #   mode: replicated
    #   replicas: 2
    depends_on:
      - rethinkdb
      - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
    networks:
      - default
    volumes:
      - /root/cats/redis/data:/data
  rethinkdb:
    image: rethinkdb
    networks:
      - default
    volumes:
      - /root/cats/rethinkdb/data:/data
  ssh:
    image: corbinu/ssh-server
    networks:
      - default
    volumes:
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
